// components/blocks/DifferentialsBlock.tsx
import { Eyebrow } from '@/components/blocks/shared/Eyebrow'
import { Section } from '@/components/blocks/shared/Section'
import { resolveBackground } from '@/lib/background'
import type { DifferentialsBlock as DifferentialsBlockProps } from '@/lib/types/blocks'

export function DifferentialsBlock({
  anchorId,
  background,
  eyebrow,
  headline,
  text,
  items,
}: DifferentialsBlockProps) {
  const resolved = resolveBackground(background)

  // Editors write paragraphs as blank-line-separated text in the JSON editor;
  // rendering them as one <p> would run them together.
  const paragraphs = text?.split(/\n\s*\n/).filter(Boolean) ?? []

  return (
    <Section id={anchorId} style={resolved.style} className={resolved.className}>
      <div className="grid items-start gap-16 lg:grid-cols-2">
        <div>
          {eyebrow ? <Eyebrow>{eyebrow}</Eyebrow> : null}
          <h2 className="text-ink mb-6 text-[clamp(2rem,3.4vw,2.7rem)]">{headline}</h2>
          {paragraphs.map((paragraph) => (
            <p key={paragraph} className="text-ink-dim mb-5 text-[1.02rem] last:mb-0">
              {paragraph}
            </p>
          ))}
        </div>

        <ul className="flex list-none flex-col gap-5">
          {items.map((item) => (
            <li
              key={item.text}
              className="bg-surface border-surface-line text-ink-dim flex gap-4 rounded border p-5 text-[0.95rem]"
            >
              {item.tag ? (
                <span className="font-tenant-secondary text-tenant-primary shrink-0 pt-0.5 text-[0.7rem]">
                  {item.tag}
                </span>
              ) : null}
              {item.icon ? <span aria-hidden="true">{item.icon}</span> : null}
              <span>{item.text}</span>
            </li>
          ))}
        </ul>
      </div>
    </Section>
  )
}

// packages/ui/src/blocks/DifferentialsBlock.vue
<script setup lang="ts">
import type { DifferentialsBlock } from '@forge-pages/types'
import { computed } from 'vue'
import { resolveBackground } from '../utils/background'

const props = defineProps<DifferentialsBlock>()

const resolved = computed(() => resolveBackground(props.background))
const isDark = computed(() => {
  const t = props.background?.type
  return t === 'solid' || t === 'gradient' || t === 'glass' || t === 'image'
})
</script>

<template>
  <section :class="resolved.classes" :style="resolved.style">
    <div class="container mx-auto px-4 py-20">
      <div class="max-w-2xl mx-auto text-center mb-12">
        <h2 class="text-3xl md:text-4xl font-bold" :class="isDark ? 'text-white' : 'text-gray-900'">
          {{ props.headline }}
        </h2>
        <p v-if="props.text" class="mt-4 text-lg" :class="isDark ? 'text-white/70' : 'text-gray-600'">
          {{ props.text }}
        </p>
      </div>
      <ul class="flex flex-col gap-4 max-w-2xl mx-auto">
        <li
          v-for="(item, i) in props.items"
          :key="i"
          class="flex items-start gap-4 rounded-lg border px-5 py-4"
          :class="isDark ? 'bg-white/5 border-white/10' : 'bg-black/[0.03] border-black/10'"
        >
          <span
            v-if="item.tag"
            class="mt-0.5 shrink-0 rounded-full px-3 py-1 text-xs font-bold uppercase tracking-wide bg-[var(--tenant-secondary)] text-white"
          >
            {{ item.tag }}
          </span>
          <span
            v-else
            class="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--tenant-secondary)] text-white"
          >
            {{ item.icon }}
          </span>
          <span :class="isDark ? 'text-white/80' : 'text-gray-700'">{{ item.text }}</span>
        </li>
      </ul>
    </div>
  </section>
</template>
