// components/blocks/HeaderBlock.tsx
import { CtaButton } from '@/components/blocks/shared/CtaButton'
import { MobileMenu } from '@/components/blocks/shared/MobileMenu'
import { HEADER_BACKGROUND_FALLBACK, resolveBackground } from '@/lib/background'
import type { HeaderBlock as HeaderBlockProps } from '@/lib/types/blocks'

/** WhatsApp deep link, or the plain link when no number is configured. */
function resolveCtaHref({
  ctaWhatsapp,
  ctaMessage,
  ctaLink,
}: Pick<HeaderBlockProps, 'ctaWhatsapp' | 'ctaMessage' | 'ctaLink'>) {
  if (ctaWhatsapp) {
    const text = ctaMessage ? `?text=${encodeURIComponent(ctaMessage)}` : ''
    return `https://wa.me/${ctaWhatsapp}${text}`
  }

  return ctaLink ?? '#contato'
}

export function HeaderBlock({
  variant = 'default',
  background,
  logo,
  menuLinks,
  ctaLabel,
  ctaWhatsapp,
  ctaMessage,
  ctaLink,
}: HeaderBlockProps) {
  // Unlike every other block, an unset background falls back to a surface rather
  // than transparent — a sticky header over scrolling content must stay legible.
  const resolved = resolveBackground(background ?? HEADER_BACKGROUND_FALLBACK)
  const ctaHref = resolveCtaHref({ ctaWhatsapp, ctaMessage, ctaLink })

  return (
    <header
      style={resolved.style}
      className={`border-surface-line fixed top-0 right-0 left-0 z-50 flex items-center border-b px-[6vw] py-4 ${resolved.className} ${
        variant === 'centered' ? 'justify-center gap-10' : 'justify-between'
      }`}
    >
      <a href="#hero" className="flex items-center gap-2.5">
        {logo ? (
          // biome-ignore lint/performance/noImgElement: SVG logo, no optimisation to gain
          <img
            src={logo.url}
            alt={logo.alternativeText ?? ''}
            className="h-8 w-auto object-contain"
          />
        ) : null}
      </a>

      <nav className="hidden items-center gap-8 lg:flex">
        {menuLinks.map((link) => (
          <a
            key={link.url}
            href={link.url}
            className="font-tenant-secondary text-ink-dim hover:text-tenant-primary text-[0.82rem] tracking-[0.04em] uppercase no-underline transition-colors"
          >
            {link.label}
          </a>
        ))}
      </nav>

      <div className="hidden lg:block">
        <CtaButton href={ctaHref} label={ctaLabel} size="sm" />
      </div>

      <MobileMenu links={menuLinks} ctaLabel={ctaLabel} ctaHref={ctaHref} />
    </header>
  )
}

// packages/ui/src/blocks/HeaderBlock.vue
<script setup lang="ts">
import type { HeaderBlock } from '@forge-pages/types'
import { computed } from 'vue'
import { resolveBackground } from '../utils/background'

const props = defineProps<HeaderBlock>()

const isCentered = computed(() => props.variant === 'centered')

// A sticky header needs *some* backdrop to stay legible over scrolling content —
// unlike in-flow blocks, "no background config" here means today's white glass
// bar, not fully transparent.
const resolved = computed(() =>
  resolveBackground(
    props.background ?? { type: 'glass', colorToken: 'custom', customColor: '#ffffff' },
  ),
)

const waLink = (phone: string, message?: string): string => {
  const digits = phone.replace(/\D/g, '')
  const base = `https://wa.me/${digits}`
  return message ? `${base}?text=${encodeURIComponent(message)}` : base
}

const ctaHref = computed(() =>
  props.ctaLink
    ? props.ctaLink
    : props.ctaWhatsapp
      ? waLink(props.ctaWhatsapp, props.ctaMessage)
      : '#',
)
</script>

<template>
  <header
    class="sticky top-0 z-50 border-b border-gray-100"
    :class="resolved.classes"
    :style="resolved.style"
  >
    <div
      class="container mx-auto px-4 h-16 items-center gap-4"
      :class="isCentered ? 'grid grid-cols-[auto_1fr_auto]' : 'flex justify-between'"
    >
      <img v-if="props.logo" :src="props.logo.url" :alt="props.logo.alternativeText ?? ''" class="h-8 w-auto" />
      <nav
        v-if="props.menuLinks?.length"
        class="hidden md:flex items-center gap-6"
        :class="isCentered ? 'justify-self-center' : ''"
      >
        <a
          v-for="link in props.menuLinks"
          :key="link.url"
          :href="link.url"
          class="text-sm font-medium text-gray-700 hover:text-[var(--tenant-primary)] transition-colors"
        >
          {{ link.label }}
        </a>
      </nav>
      <a
        :href="ctaHref"
        :target="props.ctaLink ? undefined : '_blank'"
        :rel="props.ctaLink ? undefined : 'noopener'"
        class="px-5 py-2 rounded-lg text-sm font-semibold text-white bg-[var(--tenant-primary)] hover:opacity-90 transition-opacity"
        :class="isCentered ? 'justify-self-end' : ''"
      >
        {{ props.ctaLabel }}
      </a>
    </div>
  </header>
</template>
