// components/blocks/PricingBlock.tsx
import { CtaButton } from '@/components/blocks/shared/CtaButton'
import { Eyebrow } from '@/components/blocks/shared/Eyebrow'
import { Section } from '@/components/blocks/shared/Section'
import type { PricingBlock as PricingBlockProps } from '@/lib/types/blocks'

export function PricingBlock({
  anchorId,
  eyebrow,
  headline,
  subheadline,
  plans,
  note,
}: PricingBlockProps) {
  return (
    <Section id={anchorId}>
      <div className="mb-16 max-w-[640px]">
        {eyebrow ? <Eyebrow>{eyebrow}</Eyebrow> : null}
        <h2 className="text-ink text-[clamp(2rem,3.6vw,2.9rem)]">{headline}</h2>
        {subheadline ? <p className="text-ink-dim mt-4 text-[1.02rem]">{subheadline}</p> : null}
      </div>

      <div className="grid items-stretch gap-8 lg:grid-cols-2">
        {plans.map((plan) => (
          <article
            key={plan.title}
            className={`bg-surface relative flex flex-col rounded-lg border p-9 ${
              plan.featured
                ? 'border-tenant-primary bg-[linear-gradient(180deg,color-mix(in_srgb,var(--tenant-primary)_7%,transparent),var(--color-surface)_30%)]'
                : 'border-surface-line'
            }`}
          >
            {plan.badge ? (
              <span className="font-tenant-secondary text-tenant-background absolute -top-3 left-9 rounded-full bg-[linear-gradient(135deg,var(--tenant-primary),var(--tenant-secondary))] px-3 py-1.5 text-[0.68rem] font-bold tracking-[0.06em] uppercase">
                {plan.badge}
              </span>
            ) : null}

            {plan.eyebrow ? (
              <div className="font-tenant-secondary text-tenant-primary mb-2.5 text-[0.72rem] tracking-[0.12em] uppercase">
                {plan.eyebrow}
              </div>
            ) : null}

            <h3 className="text-ink mb-2 text-[1.7rem]">{plan.title}</h3>
            {plan.description ? (
              <p className="text-ink-dim mb-7 text-[0.92rem]">{plan.description}</p>
            ) : null}

            <div className="font-tenant-secondary text-tenant-secondary mb-8 text-[2.1rem] font-bold">
              {plan.price}
            </div>

            <ul className="mb-8 flex grow list-none flex-col gap-3.5">
              {plan.features.map((feature) => (
                <li key={feature.text} className="text-ink-dim flex gap-3 text-[0.92rem]">
                  <span aria-hidden="true" className="text-tenant-primary shrink-0">
                    ✓
                  </span>
                  {feature.text}
                </li>
              ))}
            </ul>

            <CtaButton
              href={plan.ctaLink}
              label={plan.ctaLabel}
              tone={plan.featured ? 'primary' : 'ghost'}
            />
          </article>
        ))}
      </div>

      {note ? (
        <p className="font-tenant-secondary text-ink-muted mt-8 text-center text-[0.85rem]">
          {note}
        </p>
      ) : null}
    </Section>
  )
}

// packages/ui/src/blocks/PricingBlock.vue
<script setup lang="ts">
import type { PricingBlock } from '@forge-pages/types'

const props = defineProps<PricingBlock>()
</script>

<template>
  <section class="bg-white">
    <div class="container mx-auto px-4 py-20">
      <div class="max-w-2xl mx-auto text-center mb-12">
        <h2 class="text-3xl md:text-4xl font-bold text-gray-900">{{ props.headline }}</h2>
        <p v-if="props.subheadline" class="mt-4 text-lg text-gray-600">{{ props.subheadline }}</p>
      </div>
      <div class="grid gap-8 md:grid-cols-2 max-w-4xl mx-auto items-start">
        <div
          v-for="(plan, i) in props.plans"
          :key="i"
          class="relative p-8 rounded-2xl border shadow-sm"
          :class="
            plan.featured
              ? 'border-[var(--tenant-primary)] shadow-lg md:scale-105'
              : 'border-gray-100'
          "
        >
          <span
            v-if="plan.badge"
            class="absolute -top-3 left-8 rounded-full px-3 py-1 text-xs font-bold uppercase tracking-wide text-white bg-[var(--tenant-primary)]"
          >
            {{ plan.badge }}
          </span>
          <p v-if="plan.eyebrow" class="text-sm font-semibold text-[var(--tenant-secondary)] mb-2">
            {{ plan.eyebrow }}
          </p>
          <h3 class="text-xl font-semibold text-gray-900 mb-2">{{ plan.title }}</h3>
          <p v-if="plan.description" class="text-gray-600 mb-4">{{ plan.description }}</p>
          <p class="text-2xl font-bold text-gray-900 mb-6">{{ plan.price }}</p>
          <ul class="grid gap-3 mb-8">
            <li v-for="(feature, fi) in plan.features" :key="fi" class="flex items-start gap-2 text-gray-700">
              <span class="mt-1 text-[var(--tenant-secondary)]">✓</span>
              <span>{{ feature.text }}</span>
            </li>
          </ul>
          <a
            :href="plan.ctaLink"
            class="block w-full text-center px-6 py-3 rounded-lg font-semibold text-white bg-[var(--tenant-primary)] hover:opacity-90 transition-opacity"
          >
            {{ plan.ctaLabel }}
          </a>
        </div>
      </div>
      <p v-if="props.note" class="mt-10 text-center text-sm text-gray-500 max-w-2xl mx-auto">
        {{ props.note }}
      </p>
    </div>
  </section>
</template>
