// packages/ui/src/blocks/FooterBlock.vue
<script setup lang="ts">
import type { FooterBlock } from '@forge-pages/types'

const props = defineProps<FooterBlock>()
</script>

<template>
  <footer class="bg-gray-900 text-gray-300">
    <div class="container mx-auto px-4 py-14 grid gap-10 md:grid-cols-4">
      <div class="md:col-span-2">
        <img v-if="props.logo" :src="props.logo.url" :alt="props.logo.alternativeText ?? ''" class="h-8 w-auto mb-4" />
        <p v-if="props.description" class="max-w-sm text-sm text-gray-400">{{ props.description }}</p>
      </div>

      <div v-if="props.links?.length">
        <h3 class="text-white font-semibold mb-4">Links</h3>
        <ul class="space-y-2 text-sm">
          <li v-for="link in props.links" :key="link.url">
            <a :href="link.url" class="hover:text-white transition-colors">{{ link.label }}</a>
          </li>
        </ul>
      </div>

      <div>
        <h3 v-if="props.phones?.length" class="text-white font-semibold mb-4">Contato</h3>
        <ul v-if="props.phones?.length" class="space-y-2 text-sm">
          <li v-for="(phone, i) in props.phones" :key="i">
            <span v-if="phone.label" class="text-gray-500">{{ phone.label }}: </span>{{ phone.number }}
          </li>
        </ul>
        <p v-if="props.schedule" class="mt-4 text-sm text-gray-400">{{ props.schedule }}</p>
        <div v-if="props.socialLinks?.length" class="mt-4 flex gap-3">
          <a
            v-for="social in props.socialLinks"
            :key="social.url"
            :href="social.url"
            target="_blank"
            rel="noopener"
            class="text-gray-400 hover:text-white transition-colors"
          >
            {{ social.platform }}
          </a>
        </div>
      </div>
    </div>

    <div class="border-t border-gray-800">
      <div class="container mx-auto px-4 py-6 flex flex-wrap items-center justify-between gap-2 text-sm text-gray-500">
        <span>{{ props.copyright }}</span>
        <a v-if="props.privacyLink" :href="props.privacyLink" class="hover:text-white transition-colors">
          Política de Privacidade
        </a>
      </div>
    </div>
  </footer>
</template>

// components/blocks/FooterBlock.tsx
import type { FooterBlock as FooterBlockProps } from '@/lib/types/blocks'

export function FooterBlock({
  logo,
  description,
  links,
  phones,
  schedule,
  socialLinks,
  copyright,
  privacyLink,
}: FooterBlockProps) {
  const hasDetails =
    Boolean(logo || description) || links.length > 0 || phones.length > 0 || socialLinks.length > 0

  return (
    <footer className="border-surface-line mx-auto max-w-[1400px] border-t px-[8vw] py-10">
      {hasDetails ? (
        <div className="mb-8 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          <div>
            {logo ? (
              // biome-ignore lint/performance/noImgElement: SVG logo, no optimisation to gain
              <img
                src={logo.url}
                alt={logo.alternativeText ?? ''}
                className="mb-4 h-8 w-auto object-contain"
              />
            ) : null}
            {description ? <p className="text-ink-dim text-[0.88rem]">{description}</p> : null}
          </div>

          {links.length > 0 ? (
            <nav className="flex flex-col gap-2.5">
              {links.map((link) => (
                <a
                  key={link.url}
                  href={link.url}
                  className="font-tenant-secondary text-ink-dim hover:text-tenant-primary text-[0.78rem] tracking-[0.04em] uppercase no-underline transition-colors"
                >
                  {link.label}
                </a>
              ))}
            </nav>
          ) : null}

          <div className="flex flex-col gap-2.5">
            {phones.map((phone) => (
              <a
                key={phone.number}
                href={`tel:${phone.number.replace(/\D/g, '')}`}
                className="text-ink-dim text-[0.88rem] no-underline"
              >
                {phone.label ? `${phone.label}: ` : ''}
                {phone.number}
              </a>
            ))}
            {schedule ? <p className="text-ink-muted text-[0.78rem]">{schedule}</p> : null}
            {socialLinks.length > 0 ? (
              <div className="mt-2 flex gap-4">
                {socialLinks.map((social) => (
                  <a
                    key={social.url}
                    href={social.url}
                    className="font-tenant-secondary text-ink-dim hover:text-tenant-primary text-[0.78rem] uppercase no-underline transition-colors"
                  >
                    {social.platform}
                  </a>
                ))}
              </div>
            ) : null}
          </div>
        </div>
      ) : null}

      <div className="font-tenant-secondary text-ink-muted flex flex-wrap justify-center gap-4 text-center text-[0.75rem] tracking-[0.04em]">
        <span>{copyright}</span>
        {privacyLink ? (
          <a
            href={privacyLink}
            className="hover:text-tenant-primary no-underline transition-colors"
          >
            Política de privacidade
          </a>
        ) : null}
      </div>
    </footer>
  )
}
