// packages/ui/src/blocks/HeroBlock.vue
<script setup lang="ts">
import type { HeroBlock } from '@forge-pages/types'
import { computed } from 'vue'
import BackgroundParticles from '../components/BackgroundParticles.vue'
import { resolveBackground } from '../utils/background'

const props = defineProps<HeroBlock>()

const isCentered = computed(() => props.variant === 'centered')
const hasParticles = computed(() => props.background?.effect === 'particles')
const resolved = computed(() => resolveBackground(props.background))

// Fills that put an actual color/image behind the text need light text; the
// presentation's 'centered' look is dark by convention, but text color should follow
// the actual resolved background, not the layout variant — a tenant could pick
// 'centered' with a light background too.
const isDark = computed(() => {
  const t = props.background?.type
  return t === 'solid' || t === 'gradient' || t === 'glass' || t === 'image'
})
</script>

<template>
  <section
    class="relative min-h-[80vh] flex items-center overflow-hidden"
    :class="[resolved.classes, isCentered ? 'justify-center text-center' : '']"
    :style="resolved.style"
  >
    <BackgroundParticles v-if="hasParticles" />
    <div
      class="relative z-10 container mx-auto px-4 py-16"
      :class="isCentered ? 'max-w-2xl' : 'grid md:grid-cols-2 gap-12 items-center'"
    >
      <div>
        <span
          v-if="props.badgeText"
          class="inline-block mb-4 px-4 py-1 rounded-full text-sm font-semibold bg-[var(--tenant-primary)] text-white"
        >
          {{ props.badgeText }}
        </span>
        <h1
          class="text-4xl md:text-5xl font-bold mb-4 leading-tight"
          :class="isDark ? 'text-white' : 'text-gray-900'"
        >
          {{ props.headline }}
        </h1>
        <img
          v-if="props.image && isCentered"
          :src="props.image.url"
          :alt="props.imageAlt ?? props.image.alternativeText ?? props.headline"
          class="mx-auto mb-8 h-auto w-full max-w-md"
          loading="eager"
        />
        <p class="text-xl mb-8" :class="isDark ? 'text-white/70' : 'text-gray-600'">
          {{ props.subheadline }}
        </p>
        <div class="flex flex-wrap gap-4" :class="isCentered ? 'justify-center' : ''">
          <a
            :href="props.ctaPrimaryLink"
            class="px-8 py-4 rounded-lg font-semibold text-white bg-[var(--tenant-primary)] hover:opacity-90 transition-opacity"
          >
            {{ props.ctaPrimaryLabel }}
          </a>
          <a
            v-if="props.ctaSecondaryLabel && props.ctaSecondaryLink"
            :href="props.ctaSecondaryLink"
            class="px-8 py-4 rounded-lg font-semibold border-2 transition-colors"
            :class="
              isDark
                ? 'border-white/20 text-white hover:bg-white/5'
                : 'border-[var(--tenant-primary)] text-[var(--tenant-primary)] hover:bg-gray-50'
            "
          >
            {{ props.ctaSecondaryLabel }}
          </a>
        </div>
      </div>
      <div v-if="props.image && !isCentered">
        <img
          :src="props.image.url"
          :alt="props.imageAlt ?? props.image.alternativeText ?? ''"
          class="w-full h-auto rounded-xl shadow-2xl"
          loading="eager"
        />
      </div>
    </div>
  </section>
</template>

// components/blocks/HeroBlock.tsx
import { BackgroundParticles } from '@/components/blocks/shared/BackgroundParticles'
import { CtaButton } from '@/components/blocks/shared/CtaButton'
import { resolveBackground } from '@/lib/background'
import type { HeroBlock as HeroBlockProps } from '@/lib/types/blocks'

export function HeroBlock({
  anchorId,
  variant = 'default',
  background,
  badgeText,
  headline,
  subheadline,
  ctaPrimaryLabel,
  ctaPrimaryLink,
  ctaSecondaryLabel,
  ctaSecondaryLink,
  image,
  imageAlt,
}: HeroBlockProps) {
  const resolved = resolveBackground(background)
  const centered = variant === 'centered'

  return (
    <section
      id={anchorId}
      style={resolved.style}
      className={`relative flex min-h-screen flex-col justify-center px-[8vw] pt-24 pb-16 ${resolved.className} ${
        centered ? 'items-center text-center' : 'items-start'
      }`}
    >
      {background?.effect === 'particles' ? <BackgroundParticles /> : null}

      <div
        className={`relative z-10 mx-auto flex w-full max-w-[1400px] flex-col ${
          centered ? 'items-center' : 'items-start'
        }`}
      >
        {image ? (
          // Intentionally a plain <img>: the logo is an SVG, so there is nothing
          // for next/image to optimise and OpenNext's image handling is a known
          // rough edge on Workers (ADR-0001).
          // biome-ignore lint/performance/noImgElement: SVG logo, no optimisation to gain
          <img
            src={image.url}
            alt={image.alternativeText ?? imageAlt ?? ''}
            className="mb-7 h-auto w-[min(440px,80vw)] object-contain drop-shadow-[0_0_30px_color-mix(in_srgb,var(--tenant-primary)_35%,transparent)]"
          />
        ) : null}

        {badgeText ? (
          <span className="font-tenant-secondary border-surface-line text-ink-dim mb-6 rounded-full border px-4 py-1.5 text-[0.72rem] tracking-[0.12em] uppercase">
            {badgeText}
          </span>
        ) : null}

        <h1 className="text-ink text-[clamp(2rem,4.4vw,3.4rem)]">{headline}</h1>

        <p
          className={`text-ink-dim mt-6 mb-10 max-w-[560px] text-[1.15rem] font-light ${
            centered ? 'text-center' : ''
          }`}
        >
          {subheadline}
        </p>

        <div className={`flex flex-wrap gap-4 ${centered ? 'justify-center' : ''}`}>
          <CtaButton href={ctaPrimaryLink} label={ctaPrimaryLabel} />
          {ctaSecondaryLabel && ctaSecondaryLink ? (
            <CtaButton href={ctaSecondaryLink} label={ctaSecondaryLabel} tone="ghost" />
          ) : null}
        </div>
      </div>
    </section>
  )
}
