// packages/ui/src/blocks/StatsBlock.vue
<script setup lang="ts">
import type { StatsBlock } from '@forge-pages/types'

const props = defineProps<StatsBlock>()
</script>

<template>
  <section class="bg-[var(--tenant-primary)] text-white">
    <div class="container mx-auto px-4 py-14 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
      <div v-for="(item, i) in props.items" :key="i">
        <div class="text-4xl md:text-5xl font-bold">{{ item.number }}</div>
        <div class="mt-2 text-sm uppercase tracking-wide opacity-80">{{ item.label }}</div>
      </div>
    </div>
  </section>
</template>

// components/blocks/StatsBlock.tsx
import type { StatsBlock as StatsBlockProps } from '@/lib/types/blocks'

export function StatsBlock({ anchorId, items }: StatsBlockProps) {
  return (
    <section id={anchorId} className="mx-auto w-full max-w-[1400px] px-[8vw] py-16">
      <div className="grid grid-cols-2 gap-8 sm:grid-cols-4">
        {items.map((item) => (
          <div key={item.label} className="text-center">
            <div className="font-tenant-secondary text-tenant-secondary text-[2.4rem] font-bold">
              {item.number}
            </div>
            <div className="text-ink-dim mt-2 text-[0.85rem] tracking-[0.04em] uppercase">
              {item.label}
            </div>
          </div>
        ))}
      </div>
    </section>
  )
}
