// packages/ui/src/blocks/TestimonialsBlock.vue
<script setup lang="ts">
import type { TestimonialsBlock } from '@forge-pages/types'

const props = defineProps<TestimonialsBlock>()
</script>

<template>
  <section class="bg-gray-50">
    <div class="container mx-auto px-4 py-20">
      <h2 class="text-3xl md:text-4xl font-bold text-gray-900 text-center mb-12">
        {{ props.headline }}
      </h2>
      <div class="grid gap-8 md:grid-cols-3">
        <figure
          v-for="(item, i) in props.items"
          :key="i"
          class="p-8 rounded-2xl bg-white border border-gray-100 shadow-sm flex flex-col"
        >
          <div v-if="item.rating" class="mb-3 text-[var(--tenant-primary)]" aria-label="rating">
            <span v-for="star in item.rating" :key="star">★</span>
          </div>
          <blockquote class="text-gray-700 flex-1">"{{ item.text }}"</blockquote>
          <figcaption class="mt-6 flex items-center gap-3">
            <img
              v-if="item.photo"
              :src="item.photo.url"
              :alt="item.photo.alternativeText ?? item.name"
              class="h-10 w-10 rounded-full object-cover"
            />
            <div>
              <div class="font-semibold text-gray-900">{{ item.name }}</div>
              <div v-if="item.role" class="text-sm text-gray-500">{{ item.role }}</div>
            </div>
          </figcaption>
        </figure>
      </div>
    </div>
  </section>
</template>

// components/blocks/TestimonialsBlock.tsx
import { Section } from '@/components/blocks/shared/Section'
import type { TestimonialsBlock as TestimonialsBlockProps } from '@/lib/types/blocks'

function Stars({ rating }: { rating: number }) {
  const rounded = Math.round(rating)
  return (
    <div aria-hidden="true" className="text-tenant-secondary mb-3 text-[0.9rem]">
      {'★'.repeat(rounded)}
      {'☆'.repeat(5 - rounded)}
    </div>
  )
}

export function TestimonialsBlock({ anchorId, headline, items }: TestimonialsBlockProps) {
  return (
    <Section id={anchorId}>
      <h2 className="text-ink mb-16 text-[clamp(2rem,3.6vw,2.9rem)]">{headline}</h2>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {items.map((item) => (
          <article
            key={item.name}
            className="bg-surface border-surface-line flex flex-col rounded-md border p-7"
          >
            {typeof item.rating === 'number' ? <Stars rating={item.rating} /> : null}

            <p className="text-ink-dim mb-6 grow text-[0.95rem]">&ldquo;{item.text}&rdquo;</p>

            <div className="flex items-center gap-3">
              {item.photo ? (
                // biome-ignore lint/performance/noImgElement: next/image has known gaps on Cloudflare Workers (ADR-0001)
                <img
                  src={item.photo.url}
                  alt={item.photo.alternativeText ?? ''}
                  className="h-11 w-11 rounded-full object-cover"
                />
              ) : null}
              <div>
                <div className="text-ink text-[0.92rem] font-semibold">{item.name}</div>
                {item.role ? <div className="text-ink-muted text-[0.8rem]">{item.role}</div> : null}
              </div>
            </div>
          </article>
        ))}
      </div>
    </Section>
  )
}
